// Mock data for SettleTrack case database
export interface Case {
  id: string;
  name: string;
  docketId: string;
  court: string;
  state: string;
  year: number;
  settlementAmount: number;
  baseSettlementAmount?: number;
  contingentSettlementAmount?: number;
  isSettlementCapped: boolean;
  classSize: number;
  isMultiDistrictLitigation: boolean;
  piiAffected: string[];
  causeOfBreach: string;
  classType: string[];
  hasMinorSubclass: boolean;
  defenseCounsel: string;
  plaintiffCounsel: string;
  judgeName: string;
  settlementType: "Preliminary" | "Final";
  date: string;
  summary: string;
  attorneyFeesMethod: "Percentage" | "Lodestar";
  attorneyFeesPercentage?: number;
  attorneyFeesPaidFromFund: boolean;
  lodestardAmount?: number;
  multiplier?: number;
  attorneyFeesReimbursement?: number;
  attorneyFeesReimbursementFromFund: boolean;
  supplementalReimbursement?: number;
  classRepServiceAwards?: number;
  classRepAwardsFromFund: boolean;
  claimsAdminCosts?: number;
  claimsAdminCostsFromFund: boolean;
  baseCashCompensation?: number;
  maxReimbursementOutOfPocket?: number;
  maxReimbursementDocumentedTime?: number;
  maxHoursDocumented?: number;
  ratePerHourDocumented?: number;
  maxReimbursementUndocumented?: number;
  maxHoursUndocumented?: number;
  ratePerHourUndocumented?: number;
  allowBothDocAndUndoc: boolean;
  hasProRataAdjustment: boolean;
  proRataAmount?: number;
  claimsSubmitted: number;
  claimsSubmittedPercent: number;
  injunctiveRelief: string[];
  injunctiveReliefAmount?: number;
  thirdPartyAssessments?: string[];
  creditMonitoring: boolean;
  creditMonitoringAmount?: number;
  excessFundsDisposition?: "Redistribution" | "Cy pres" | "Reversion";
}

export const mockCases: Case[] = [
  {
    id: "1",
    name: "In re Christie's Data Breach Litigation",
    docketId: "1:2024cv04221",
    court: "S.D.N.Y.",
    state: "New York",
    year: 2024,
    settlementAmount: 8500000,
    baseSettlementAmount: 7500000,
    contingentSettlementAmount: 1000000,
    isSettlementCapped: true,
    classSize: 500000,
    isMultiDistrictLitigation: false,
    piiAffected: ["Name", "Address", "Email", "Phone"],
    causeOfBreach: "Ransomware",
    classType: ["Consumers"],
    hasMinorSubclass: false,
    defenseCounsel: "Williams & Connolly LLP",
    plaintiffCounsel: "Lieff Cabraser Heimann & Bernstein LLP",
    judgeName: "Judge Sarah Thompson",
    settlementType: "Final",
    date: "2024-12-15",
    summary:
      "Class action settlement for data breach affecting customer personal information",
    attorneyFeesMethod: "Percentage",
    attorneyFeesPercentage: 25,
    attorneyFeesPaidFromFund: true,
    attorneyFeesReimbursement: 150000,
    attorneyFeesReimbursementFromFund: true,
    supplementalReimbursement: 50000,
    classRepServiceAwards: 15000,
    classRepAwardsFromFund: true,
    claimsAdminCosts: 300000,
    claimsAdminCostsFromFund: true,
    baseCashCompensation: 125,
    maxReimbursementOutOfPocket: 5000,
    maxReimbursementDocumentedTime: 2000,
    maxHoursDocumented: 40,
    ratePerHourDocumented: 50,
    maxReimbursementUndocumented: 500,
    maxHoursUndocumented: 10,
    ratePerHourUndocumented: 50,
    allowBothDocAndUndoc: false,
    hasProRataAdjustment: true,
    proRataAmount: 200,
    claimsSubmitted: 125000,
    claimsSubmittedPercent: 25,
    injunctiveRelief: [
      "Employee training",
      "Multi-factor authentication",
      "Penetration testing",
      "Data encryption",
      "Vulnerability scanning",
    ],
    injunctiveReliefAmount: 1500000,
    thirdPartyAssessments: ["SOC 2", "NIST"],
    creditMonitoring: true,
    creditMonitoringAmount: 2000000,
    excessFundsDisposition: "Cy pres",
  },
  {
    id: "2",
    name: "Smith v. TechCorp Privacy Settlement",
    docketId: "3:2024cv02156",
    court: "N.D. Cal.",
    state: "California",
    year: 2024,
    settlementAmount: 12300000,
    baseSettlementAmount: 10000000,
    contingentSettlementAmount: 2300000,
    isSettlementCapped: false,
    classSize: 2500000,
    isMultiDistrictLitigation: true,
    piiAffected: ["Name", "SSN", "Address", "Payment Info"],
    causeOfBreach: "Phishing Attack",
    classType: ["Consumers"],
    hasMinorSubclass: true,
    defenseCounsel: "Gibson, Dunn & Crutcher LLP",
    plaintiffCounsel: "Hagens Berman Sobol Shapiro LLP",
    judgeName: "Judge Michael Chen",
    settlementType: "Final",
    date: "2024-12-10",
    summary:
      "Major technology company privacy settlement for unauthorized data collection",
    attorneyFeesMethod: "Lodestar",
    attorneyFeesPaidFromFund: true,
    lodestardAmount: 2500000,
    multiplier: 1.5,
    attorneyFeesReimbursement: 200000,
    attorneyFeesReimbursementFromFund: false,
    supplementalReimbursement: 75000,
    classRepServiceAwards: 20000,
    classRepAwardsFromFund: false,
    claimsAdminCosts: 450000,
    claimsAdminCostsFromFund: true,
    baseCashCompensation: 75,
    maxReimbursementOutOfPocket: 3500,
    maxReimbursementDocumentedTime: 1500,
    maxHoursDocumented: 30,
    ratePerHourDocumented: 50,
    maxReimbursementUndocumented: 250,
    maxHoursUndocumented: 5,
    ratePerHourUndocumented: 50,
    allowBothDocAndUndoc: true,
    hasProRataAdjustment: false,
    claimsSubmitted: 750000,
    claimsSubmittedPercent: 30,
    injunctiveRelief: [
      "Board oversight",
      "Vendor requirements",
      "Data encryption",
      "Multi-factor authentication",
      "Cloud governance",
      "Employee training",
    ],
    injunctiveReliefAmount: 2000000,
    thirdPartyAssessments: ["ISO 27001", "SOC 2"],
    creditMonitoring: true,
    creditMonitoringAmount: 3500000,
    excessFundsDisposition: "Redistribution",
  },
  {
    id: "3",
    name: "Johnson Class Action Settlement",
    docketId: "2:2024cv01789",
    court: "E.D. Tex.",
    state: "Texas",
    year: 2024,
    settlementAmount: 5200000,
    baseSettlementAmount: 5200000,
    isSettlementCapped: true,
    classSize: 800000,
    isMultiDistrictLitigation: false,
    piiAffected: ["Name", "Email", "Geolocation"],
    causeOfBreach: "System Vulnerability",
    classType: ["Consumers"],
    hasMinorSubclass: false,
    defenseCounsel: "Latham & Watkins LLP",
    plaintiffCounsel: "Robbins Geller Rudman & Dowd LLP",
    judgeName: "Judge Robert Martinez",
    settlementType: "Preliminary",
    date: "2024-12-08",
    summary: "Settlement for location tracking privacy violations",
    attorneyFeesMethod: "Percentage",
    attorneyFeesPercentage: 30,
    attorneyFeesPaidFromFund: true,
    attorneyFeesReimbursement: 100000,
    attorneyFeesReimbursementFromFund: true,
    classRepServiceAwards: 10000,
    classRepAwardsFromFund: true,
    claimsAdminCosts: 200000,
    claimsAdminCostsFromFund: true,
    baseCashCompensation: 50,
    maxReimbursementOutOfPocket: 1000,
    allowBothDocAndUndoc: false,
    hasProRataAdjustment: true,
    proRataAmount: 100,
    claimsSubmitted: 200000,
    claimsSubmittedPercent: 25,
    injunctiveRelief: [
      "Data minimization",
      "User consent improvements",
      "Data deletion",
    ],
    injunctiveReliefAmount: 500000,
    creditMonitoring: false,
    excessFundsDisposition: "Reversion",
  },
  {
    id: "4",
    name: "Davis v. HealthCare Partners",
    docketId: "1:2023cv08932",
    court: "S.D. Fla.",
    state: "Florida",
    year: 2023,
    settlementAmount: 18750000,
    baseSettlementAmount: 15000000,
    contingentSettlementAmount: 3750000,
    isSettlementCapped: true,
    classSize: 1200000,
    isMultiDistrictLitigation: false,
    piiAffected: ["Name", "SSN", "Medical Records", "Insurance Info"],
    causeOfBreach: "Insider Threat",
    classType: ["Patients"],
    hasMinorSubclass: true,
    defenseCounsel: "King & Spalding LLP",
    plaintiffCounsel: "Keller Rohrback L.L.P.",
    judgeName: "Judge Elizabeth Davis",
    settlementType: "Final",
    date: "2023-11-22",
    summary:
      "Healthcare data breach settlement affecting patient medical records",
    attorneyFeesMethod: "Percentage",
    attorneyFeesPercentage: 22,
    attorneyFeesPaidFromFund: true,
    attorneyFeesReimbursement: 250000,
    attorneyFeesReimbursementFromFund: true,
    classRepServiceAwards: 25000,
    classRepAwardsFromFund: true,
    claimsAdminCosts: 500000,
    claimsAdminCostsFromFund: true,
    baseCashCompensation: 150,
    maxReimbursementOutOfPocket: 10000,
    maxReimbursementDocumentedTime: 5000,
    maxHoursDocumented: 100,
    ratePerHourDocumented: 50,
    allowBothDocAndUndoc: true,
    hasProRataAdjustment: false,
    claimsSubmitted: 480000,
    claimsSubmittedPercent: 40,
    injunctiveRelief: [
      "Employee background checks",
      "Access controls",
      "Audit logging",
      "Employee training",
      "Board oversight",
    ],
    injunctiveReliefAmount: 3000000,
    thirdPartyAssessments: ["HIPAA", "SOC 2"],
    creditMonitoring: true,
    creditMonitoringAmount: 5000000,
    excessFundsDisposition: "Cy pres",
  },
  {
    id: "5",
    name: "Wilson v. FinanceCorp Data Breach",
    docketId: "1:2023cv05647",
    court: "S.D.N.Y.",
    state: "New York",
    year: 2023,
    settlementAmount: 15200000,
    baseSettlementAmount: 15200000,
    isSettlementCapped: false,
    classSize: 3200000,
    isMultiDistrictLitigation: true,
    piiAffected: ["Name", "SSN", "Bank Account", "Credit Card"],
    causeOfBreach: "Ransomware",
    classType: ["Consumers"],
    hasMinorSubclass: false,
    defenseCounsel: "Cravath, Swaine & Moore LLP",
    plaintiffCounsel: "Bernstein Litowitz Berger & Grossmann LLP",
    judgeName: "Judge Patricia Wilson",
    settlementType: "Final",
    date: "2023-09-15",
    summary:
      "Financial services company data breach affecting customer financial information",
    attorneyFeesMethod: "Lodestar",
    attorneyFeesPaidFromFund: true,
    lodestardAmount: 3800000,
    multiplier: 1.2,
    attorneyFeesReimbursement: 300000,
    attorneyFeesReimbursementFromFund: false,
    supplementalReimbursement: 100000,
    classRepServiceAwards: 30000,
    classRepAwardsFromFund: false,
    claimsAdminCosts: 600000,
    claimsAdminCostsFromFund: true,
    baseCashCompensation: 100,
    maxReimbursementOutOfPocket: 7500,
    maxReimbursementDocumentedTime: 3000,
    maxHoursDocumented: 60,
    ratePerHourDocumented: 50,
    maxReimbursementUndocumented: 750,
    maxHoursUndocumented: 15,
    ratePerHourUndocumented: 50,
    allowBothDocAndUndoc: false,
    hasProRataAdjustment: true,
    proRataAmount: 250,
    claimsSubmitted: 960000,
    claimsSubmittedPercent: 30,
    injunctiveRelief: [
      "SOC 2 compliance",
      "Incident response plan",
      "Data encryption",
      "Penetration testing",
      "Multi-factor authentication",
    ],
    injunctiveReliefAmount: 2500000,
    thirdPartyAssessments: ["SOC 2", "PCI DSS", "NIST"],
    creditMonitoring: true,
    creditMonitoringAmount: 8000000,
    excessFundsDisposition: "Redistribution",
  },
  {
    id: "6",
    name: "Martinez v. RetailChain Inc.",
    docketId: "2:2023cv03421",
    court: "C.D. Cal.",
    state: "California",
    year: 2023,
    settlementAmount: 9800000,
    baseSettlementAmount: 9800000,
    isSettlementCapped: true,
    classSize: 1800000,
    isMultiDistrictLitigation: false,
    piiAffected: ["Name", "Address", "Payment Info"],
    causeOfBreach: "Payment System Hack",
    classType: ["Consumers"],
    hasMinorSubclass: false,
    defenseCounsel: "O'Melveny & Myers LLP",
    plaintiffCounsel: "Milberg Coleman Bryson Phillips Grossman PLLC",
    judgeName: "Judge Carlos Rodriguez",
    settlementType: "Final",
    date: "2023-08-30",
    summary: "Retail chain payment card data breach settlement",
    attorneyFeesMethod: "Percentage",
    attorneyFeesPercentage: 28,
    attorneyFeesPaidFromFund: true,
    attorneyFeesReimbursement: 175000,
    attorneyFeesReimbursementFromFund: true,
    classRepServiceAwards: 15000,
    classRepAwardsFromFund: true,
    claimsAdminCosts: 350000,
    claimsAdminCostsFromFund: true,
    baseCashCompensation: 80,
    maxReimbursementOutOfPocket: 2500,
    allowBothDocAndUndoc: false,
    hasProRataAdjustment: true,
    proRataAmount: 150,
    claimsSubmitted: 540000,
    claimsSubmittedPercent: 30,
    injunctiveRelief: [
      "PCI DSS compliance",
      "Network segmentation",
      "Vendor requirements",
    ],
    injunctiveReliefAmount: 1000000,
    thirdPartyAssessments: ["PCI DSS"],
    creditMonitoring: true,
    creditMonitoringAmount: 2500000,
    excessFundsDisposition: "Cy pres",
  },
  {
    id: "7",
    name: "Thompson v. EducationCorp",
    docketId: "1:2022cv07854",
    court: "D. Mass.",
    state: "Massachusetts",
    year: 2022,
    settlementAmount: 6500000,
    baseSettlementAmount: 6500000,
    isSettlementCapped: true,
    classSize: 450000,
    isMultiDistrictLitigation: false,
    piiAffected: ["Name", "SSN", "Student Records"],
    causeOfBreach: "Database Misconfiguration",
    classType: ["Consumers", "Students"],
    hasMinorSubclass: true,
    defenseCounsel: "Ropes & Gray LLP",
    plaintiffCounsel: "Labaton Sucharow LLP",
    judgeName: "Judge Amanda Foster",
    settlementType: "Final",
    date: "2022-12-05",
    summary: "Educational institution student data breach settlement",
    attorneyFeesMethod: "Percentage",
    attorneyFeesPercentage: 25,
    attorneyFeesPaidFromFund: true,
    attorneyFeesReimbursement: 125000,
    attorneyFeesReimbursementFromFund: true,
    classRepServiceAwards: 12500,
    classRepAwardsFromFund: true,
    claimsAdminCosts: 250000,
    claimsAdminCostsFromFund: true,
    baseCashCompensation: 60,
    maxReimbursementOutOfPocket: 1500,
    allowBothDocAndUndoc: true,
    hasProRataAdjustment: false,
    claimsSubmitted: 135000,
    claimsSubmittedPercent: 30,
    injunctiveRelief: [
      "Security training",
      "Data governance policies",
      "Data minimization",
    ],
    injunctiveReliefAmount: 750000,
    creditMonitoring: true,
    creditMonitoringAmount: 1800000,
    excessFundsDisposition: "Reversion",
  },
  {
    id: "8",
    name: "Brown v. InsuranceCorp Settlement",
    docketId: "3:2022cv04567",
    court: "N.D. Ill.",
    state: "Illinois",
    year: 2022,
    settlementAmount: 22500000,
    baseSettlementAmount: 20000000,
    contingentSettlementAmount: 2500000,
    isSettlementCapped: false,
    classSize: 5600000,
    isMultiDistrictLitigation: true,
    piiAffected: ["Name", "SSN", "Policy Numbers", "Medical Info"],
    causeOfBreach: "Third-party Vendor",
    classType: ["Consumers"],
    hasMinorSubclass: false,
    defenseCounsel: "Skadden, Arps, Slate, Meagher & Flom LLP",
    plaintiffCounsel: "Hausfeld LLP",
    judgeName: "Judge David Kim",
    settlementType: "Final",
    date: "2022-10-18",
    summary: "Insurance company data breach through third-party vendor",
    attorneyFeesMethod: "Lodestar",
    attorneyFeesPaidFromFund: true,
    lodestardAmount: 5625000,
    multiplier: 1.0,
    attorneyFeesReimbursement: 400000,
    attorneyFeesReimbursementFromFund: true,
    supplementalReimbursement: 150000,
    classRepServiceAwards: 35000,
    classRepAwardsFromFund: false,
    claimsAdminCosts: 800000,
    claimsAdminCostsFromFund: true,
    baseCashCompensation: 125,
    maxReimbursementOutOfPocket: 5000,
    maxReimbursementDocumentedTime: 2500,
    maxHoursDocumented: 50,
    ratePerHourDocumented: 50,
    allowBothDocAndUndoc: true,
    hasProRataAdjustment: true,
    proRataAmount: 300,
    claimsSubmitted: 1680000,
    claimsSubmittedPercent: 30,
    injunctiveRelief: [
      "Vendor security requirements",
      "Regular audits",
      "Incident response",
      "Employee training",
      "Cloud governance",
    ],
    injunctiveReliefAmount: 5000000,
    thirdPartyAssessments: ["ISO 27001", "SOC 2", "NIST"],
    creditMonitoring: true,
    creditMonitoringAmount: 12000000,
    excessFundsDisposition: "Redistribution",
  },
];

export const filterOptions = {
  states: [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
  courts: [
    "S.D.N.Y.",
    "N.D. Cal.",
    "E.D. Tex.",
    "S.D. Fla.",
    "C.D. Cal.",
    "D. Mass.",
    "N.D. Ill.",
    "E.D. Pa.",
    "S.D. Cal.",
    "D.N.J.",
    "E.D.N.Y.",
    "W.D. Tex.",
    "D. Conn.",
    "D. Md.",
  ],
  piiTypes: [
    "Name",
    "Address",
    "Email",
    "Phone",
    "SSN",
    "Payment Info",
    "Medical Records",
    "Insurance Info",
    "Bank Account",
    "Credit Card",
    "Geolocation",
    "Student Records",
    "Policy Numbers",
    "Biometric Data",
  ],
  breachCauses: [
    "Ransomware",
    "Phishing Attack",
    "System Vulnerability",
    "Insider Threat",
    "Payment System Hack",
    "Database Misconfiguration",
    "Third-party Vendor",
    "Malware",
    "Social Engineering",
    "Physical Theft",
  ],
  classTypes: ["Consumers", "Employees", "Patients", "Students", "Businesses"],
  lawFirms: [
    "Williams & Connolly LLP",
    "Gibson, Dunn & Crutcher LLP",
    "Latham & Watkins LLP",
    "King & Spalding LLP",
    "Cravath, Swaine & Moore LLP",
    "O'Melveny & Myers LLP",
    "Ropes & Gray LLP",
    "Skadden, Arps, Slate, Meagher & Flom LLP",
    "Lieff Cabraser Heimann & Bernstein LLP",
    "Hagens Berman Sobol Shapiro LLP",
    "Robbins Geller Rudman & Dowd LLP",
    "Keller Rohrback L.L.P.",
    "Bernstein Litowitz Berger & Grossmann LLP",
    "Milberg Coleman Bryson Phillips Grossman PLLC",
    "Labaton Sucharow LLP",
    "Hausfeld LLP",
  ],
};

export interface SavedSearch {
  id: string;
  name: string;
  description?: string;
  filters: {
    states?: string[];
    courts?: string[];
    yearRange?: [number, number];
    settlementAmountRange?: [number, number];
    classSizeRange?: [number, number];
    piiAffected?: string[];
    causeOfBreach?: string[];
    classType?: string[];
    isMultiDistrictLitigation?: boolean;
    hasMinorSubclass?: boolean;
    settlementType?: string[];
    creditMonitoring?: boolean;
  };
  createdAt: string;
  lastUsed?: string;
  alertEnabled: boolean;
  isShared: boolean;
  createdBy: string;
  matchingCasesCount: number;
}

export const mockSavedSearches: SavedSearch[] = [
  {
    id: "1",
    name: "Data Breach > $10M",
    description: "High-value data breach settlements for precedent analysis",
    filters: {
      settlementAmountRange: [10000000, 100000000],
      causeOfBreach: ["Ransomware", "Phishing Attack", "Third-party Vendor"],
    },
    createdAt: "2024-11-01",
    lastUsed: "2024-12-15",
    alertEnabled: true,
    isShared: false,
    createdBy: "John Doe",
    matchingCasesCount: 4,
  },
  {
    id: "2",
    name: "California Class Actions",
    description: "All class action settlements in California courts",
    filters: {
      states: ["California"],
      classType: ["Consumers"],
    },
    createdAt: "2024-10-15",
    lastUsed: "2024-12-12",
    alertEnabled: false,
    isShared: true,
    createdBy: "Sarah Johnson",
    matchingCasesCount: 3,
  },
  {
    id: "3",
    name: "2024 Settlements",
    description: "Recent settlements from current year",
    filters: {
      yearRange: [2024, 2024],
    },
    createdAt: "2024-01-01",
    lastUsed: "2024-12-10",
    alertEnabled: true,
    isShared: false,
    createdBy: "John Doe",
    matchingCasesCount: 3,
  },
  {
    id: "4",
    name: "Healthcare Data Breaches",
    description: "Medical and healthcare-related privacy settlements",
    filters: {
      classType: ["Patients"],
      piiAffected: ["Medical Records", "Insurance Info"],
    },
    createdAt: "2024-09-20",
    alertEnabled: false,
    isShared: false,
    createdBy: "Michael Chen",
    matchingCasesCount: 1,
  },
];
